apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: weather-api

spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
      - name: main-api
        image: docker.pkg.github.com/zorinivana/misis_ci/api-container:$VERSION
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m