name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./TestActions/TestActions.WebApp/Dockerfile --tag ghcr.io/zorinivana/my-image-name
    - name: commit
      run: docker push ghcr.io/zorinivana/my-image-name:latest
