name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./TestActions/TestActions.WebApp/Dockerfile --tag my-image-name:$(date +%s)
    - name: Push
      run: docker push ghcr.io/zorivana/my-image-name:$(date +%s):latest
